---
label: Personal Settings
hide_body: true
fields:
- type: text
  name: template
  label: template
- type: text
  name: name
  label: name
- type: text
  name: email
  label: email
- type: text
  name: address
  label: address
- type: text
  name: phone_number
  label: phone_number
